// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: smartDoctor.proto

package smartDoctor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoctorQuestionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Question string `protobuf:"bytes,1,opt,name=Question,proto3" json:"Question,omitempty"`
}

func (x *DoctorQuestionRequest) Reset() {
	*x = DoctorQuestionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smartDoctor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorQuestionRequest) ProtoMessage() {}

func (x *DoctorQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartDoctor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorQuestionRequest.ProtoReflect.Descriptor instead.
func (*DoctorQuestionRequest) Descriptor() ([]byte, []int) {
	return file_smartDoctor_proto_rawDescGZIP(), []int{0}
}

func (x *DoctorQuestionRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type DoctorQuestionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer []byte `protobuf:"bytes,1,opt,name=Answer,proto3" json:"Answer,omitempty"`
}

func (x *DoctorQuestionResponse) Reset() {
	*x = DoctorQuestionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smartDoctor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorQuestionResponse) ProtoMessage() {}

func (x *DoctorQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smartDoctor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorQuestionResponse.ProtoReflect.Descriptor instead.
func (*DoctorQuestionResponse) Descriptor() ([]byte, []int) {
	return file_smartDoctor_proto_rawDescGZIP(), []int{1}
}

func (x *DoctorQuestionResponse) GetAnswer() []byte {
	if x != nil {
		return x.Answer
	}
	return nil
}

type DoctorQuestionListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DoctorQuestionListRequest) Reset() {
	*x = DoctorQuestionListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smartDoctor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorQuestionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorQuestionListRequest) ProtoMessage() {}

func (x *DoctorQuestionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartDoctor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorQuestionListRequest.ProtoReflect.Descriptor instead.
func (*DoctorQuestionListRequest) Descriptor() ([]byte, []int) {
	return file_smartDoctor_proto_rawDescGZIP(), []int{2}
}

type DoctorQuestionListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []byte `protobuf:"bytes,1,opt,name=List,proto3" json:"List,omitempty"`
}

func (x *DoctorQuestionListResponse) Reset() {
	*x = DoctorQuestionListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smartDoctor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorQuestionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorQuestionListResponse) ProtoMessage() {}

func (x *DoctorQuestionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smartDoctor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorQuestionListResponse.ProtoReflect.Descriptor instead.
func (*DoctorQuestionListResponse) Descriptor() ([]byte, []int) {
	return file_smartDoctor_proto_rawDescGZIP(), []int{3}
}

func (x *DoctorQuestionListResponse) GetList() []byte {
	if x != nil {
		return x.List
	}
	return nil
}

type DoctorQuestionDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *DoctorQuestionDeleteRequest) Reset() {
	*x = DoctorQuestionDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smartDoctor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorQuestionDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorQuestionDeleteRequest) ProtoMessage() {}

func (x *DoctorQuestionDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartDoctor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorQuestionDeleteRequest.ProtoReflect.Descriptor instead.
func (*DoctorQuestionDeleteRequest) Descriptor() ([]byte, []int) {
	return file_smartDoctor_proto_rawDescGZIP(), []int{4}
}

func (x *DoctorQuestionDeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DoctorQuestionDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *DoctorQuestionDeleteResponse) Reset() {
	*x = DoctorQuestionDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smartDoctor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorQuestionDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorQuestionDeleteResponse) ProtoMessage() {}

func (x *DoctorQuestionDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smartDoctor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorQuestionDeleteResponse.ProtoReflect.Descriptor instead.
func (*DoctorQuestionDeleteResponse) Descriptor() ([]byte, []int) {
	return file_smartDoctor_proto_rawDescGZIP(), []int{5}
}

func (x *DoctorQuestionDeleteResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DoctorQuestionDeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_smartDoctor_proto protoreflect.FileDescriptor

var file_smartDoctor_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72,
	0x22, 0x33, 0x0a, 0x15, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x30, 0x0a, 0x16, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x1b, 0x0a, 0x19, 0x44, 0x6f, 0x63, 0x74, 0x6f,
	0x72, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x30, 0x0a, 0x1a, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x51, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2d, 0x0a, 0x1b, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x1c, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0xbc, 0x02, 0x0a, 0x0b, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x44, 0x6f, 0x63,
	0x74, 0x6f, 0x72, 0x12, 0x59, 0x0a, 0x0e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x44, 0x6f, 0x63,
	0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x6d, 0x61, 0x72,
	0x74, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x51, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x65,
	0x0a, 0x12, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x26, 0x2e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x44, 0x6f, 0x63, 0x74,
	0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x73,
	0x6d, 0x61, 0x72, 0x74, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f,
	0x72, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6b, 0x0a, 0x14, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x28, 0x2e,
	0x73, 0x6d, 0x61, 0x72, 0x74, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74,
	0x6f, 0x72, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x44,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x44, 0x6f, 0x63,
	0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_smartDoctor_proto_rawDescOnce sync.Once
	file_smartDoctor_proto_rawDescData = file_smartDoctor_proto_rawDesc
)

func file_smartDoctor_proto_rawDescGZIP() []byte {
	file_smartDoctor_proto_rawDescOnce.Do(func() {
		file_smartDoctor_proto_rawDescData = protoimpl.X.CompressGZIP(file_smartDoctor_proto_rawDescData)
	})
	return file_smartDoctor_proto_rawDescData
}

var file_smartDoctor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_smartDoctor_proto_goTypes = []interface{}{
	(*DoctorQuestionRequest)(nil),        // 0: smartDoctor.DoctorQuestionRequest
	(*DoctorQuestionResponse)(nil),       // 1: smartDoctor.DoctorQuestionResponse
	(*DoctorQuestionListRequest)(nil),    // 2: smartDoctor.DoctorQuestionListRequest
	(*DoctorQuestionListResponse)(nil),   // 3: smartDoctor.DoctorQuestionListResponse
	(*DoctorQuestionDeleteRequest)(nil),  // 4: smartDoctor.DoctorQuestionDeleteRequest
	(*DoctorQuestionDeleteResponse)(nil), // 5: smartDoctor.DoctorQuestionDeleteResponse
}
var file_smartDoctor_proto_depIdxs = []int32{
	0, // 0: smartDoctor.SmartDoctor.DoctorQuestion:input_type -> smartDoctor.DoctorQuestionRequest
	2, // 1: smartDoctor.SmartDoctor.DoctorQuestionList:input_type -> smartDoctor.DoctorQuestionListRequest
	4, // 2: smartDoctor.SmartDoctor.DoctorQuestionDelete:input_type -> smartDoctor.DoctorQuestionDeleteRequest
	1, // 3: smartDoctor.SmartDoctor.DoctorQuestion:output_type -> smartDoctor.DoctorQuestionResponse
	3, // 4: smartDoctor.SmartDoctor.DoctorQuestionList:output_type -> smartDoctor.DoctorQuestionListResponse
	5, // 5: smartDoctor.SmartDoctor.DoctorQuestionDelete:output_type -> smartDoctor.DoctorQuestionDeleteResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_smartDoctor_proto_init() }
func file_smartDoctor_proto_init() {
	if File_smartDoctor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_smartDoctor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorQuestionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smartDoctor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorQuestionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smartDoctor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorQuestionListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smartDoctor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorQuestionListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smartDoctor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorQuestionDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smartDoctor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorQuestionDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_smartDoctor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_smartDoctor_proto_goTypes,
		DependencyIndexes: file_smartDoctor_proto_depIdxs,
		MessageInfos:      file_smartDoctor_proto_msgTypes,
	}.Build()
	File_smartDoctor_proto = out.File
	file_smartDoctor_proto_rawDesc = nil
	file_smartDoctor_proto_goTypes = nil
	file_smartDoctor_proto_depIdxs = nil
}
